[tools]
go = "1.26.2"
node = "24"
"aqua:golangci/golangci-lint" = "2.11.4"
"aqua:rhysd/actionlint" = "1.7.7"
"aqua:goreleaser/goreleaser" = "2.15.2"
"aqua:evilmartians/lefthook" = "1.8.0"

[env]
GOTOOLCHAIN = "go1.26.2"
